# Generated by Django 3.2.16 on 2022-12-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.CharField(max_length=20)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='lms.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='lms.group')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('leson', models.CharField(max_length=20)),
                ('dz', models.CharField(max_length=20)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='lms.direction')),
            ],
        ),
    ]
